/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.14%)
 * Total Accepted:    147.4K
 * Total Submissions: 277.2K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
 class Solution {

     /** Use map
     public char findTheDifference(String s, String t) {
         if (s.length() == 0) {
             return t.charAt(0);
         }

         Map<Character, Integer> countMap = new HashMap<>();

         for (char c : s.toCharArray()) {
             if (!countMap.containsKey(c)) {
                 countMap.put(c, 0);
             }

             countMap.put(c, countMap.get(c) + 1);
         }

         for (char c : t.toCharArray()) {
             if (!countMap.containsKey(c) || countMap.get(c) == 0) {
                 return c;
             }

             countMap.put(c, countMap.get(c) - 1);
         }

         return ' ';
     }
     */

     public char findTheDifference(String s, String t) {
         int baseSum = 0;
         int targetSum = 0;

         for (char c : s.toCharArray()) {
             baseSum += (int) c;
         }

         for (char c : t.toCharArray()) {
             targetSum += (int) c;
         }

         return (char) (targetSum - baseSum);
     }
 }
